Translations fixes
fle-internal/content-pack-maker pull request #67
Opened 2017-06-26 21:13 UTC by ralphiee22

- We don't need to translate strings directly, except when they have the `content` key. Also we should return untranslated items such as numbers in a list.
- When doing `ujson.dumps()`, it adds extra slashes to the string. This throws off regexes parsing those strings.
- We need to translate descriptions for videos using `htmlDescription` because some of these strings have html in them. 
- We need to translate assessment items before localizing image urls because there will be no match in the translation catalog after localization.

2017-06-27 03:31 UTC, mrpau-eduard requested changes

2017-06-27 03:31 UTC, mrpau-eduard commented on contentpacks/khanacademy.py
> +    if lang != "en" and content_catalog is not None:
The `content_catalog` and `translate_assessment_item_text` should be reference first else we will have `Unresolved reference` error.

2017-06-27 03:33 UTC, ralphiee22 commented on contentpacks/khanacademy.py
> +    if lang != "en" and content_catalog is not None:
forgot to add that! will do so now!

2017-06-27 10:02 UTC, mrpau-eduard commented on contentpacks/khanacademy.py
> +    if lang != "en" and content_catalog is not None:
Nice, I will try to build a contentpack to test it. 
thanks

2017-06-29 01:29 UTC, mrpau-eduard approved these changes

2017-06-29 01:30 UTC, mrpau-eduard commented
@benjaoming Done testing it and reviewing it. We can merge it now

2017-06-29 09:54 UTC, benjaoming commented
Fantastic work @ralphiee22

And nice with the quick reviewing and testing @mrpau-eduard ! 

Is there any improvements in the content packs because of this or does it only address changes in KA's data?

2017-06-29 09:54 UTC, merged