Retrieve subtitles from youtube instead of amara
fle-internal/content-pack-maker pull request #69
Opened 2017-07-07 11:09 UTC by mrpau-eduard

## Summary
Since Khan Academy is no longer using amara for subtitling we will download the subtitles form `YouTube` and used youtube-dl to download the subtitles.  

## TODO

- [ ] Rebuild all the language packs for testing
- [ ] Test by @radinamatic 

## Issues addressed
#66

2017-07-07 16:37 UTC, radinamatic commented
@mrpau-eduard Ping me when the contentpacks are ready!

2017-07-09 13:10 UTC, benjaoming commented on contentpacks/khanacademy.py
> +        os.system(download_cmd)
Not that important, but just so you know: Youtube-dl is actually a Python library so can be accessed directory: https://github.com/rg3/youtube-dl/blob/master/README.md#embedding-youtube-dl

2017-07-09 13:12 UTC, benjaoming requested changes

2017-07-09 13:12 UTC, benjaoming commented on requirements_dev.txt
> +youtube-dl==2017.06.12
This isn't a dev requirement? Should be in `requirements.txt`...

2017-07-13 08:21 UTC, mrpau-eduard commented
Hi @radinamatic, you can grab the language packs here
https://drive.google.com/open?id=0B-E59G3J_sXmazlqUHljaDVTcTQ

2017-07-13 08:21 UTC, mrpau-eduard commented
HI @benjaoming I will revise the code base on your comments thanks for reviewing :)

2017-07-14 02:17 UTC, radinamatic commented
@mrpau-eduard I installed the latest contentpacks, and downloaded several random videos in English, and they all correctly present the subtitles, so since I cannot actually test all 8k+, I'm giving this PR a pass! :wink: 

If we discover that some are missing, we'll take it on case-by-case basis.

On another hand (I'll separate this in a new issue if necessary), I'm still seeing (a totally useless) English subtitles on dubbed Spanish videos... :thinking:   

![xubuntu start running - oracle vm virtualbox_355](https://user-images.githubusercontent.com/1457929/28195552-366f5a86-684b-11e7-8439-f40d977026df.png)

2017-07-14 02:25 UTC, mrpau-eugene commented
@radinamatic I think you are probably using the `0.17.1` release. We disabled it in `0.17.2`

2017-07-14 02:27 UTC, radinamatic commented
Ok, I will re-test with the latest 0.17.2 installer, and report back! :+1:

2017-07-14 05:54 UTC, mrpau-eduard commented
Hi @benjaoming can you review it again? I update my `PR` base on your comments.

2017-07-18 12:40 UTC, benjaoming approved these changes

2017-07-18 12:41 UTC, benjaoming commented
Looks great! Ready to merge and start building content packs, no?

2017-07-19 05:07 UTC, radinamatic approved these changes
LGTM

2017-07-19 05:10 UTC, radinamatic commented
Re-tested with `0.17.2-rc2` installer, good to merge, but we need to fix #71 before building contentpacks again (partners in south America are expecting this).

2017-07-19 09:41 UTC, mrpau-eduard commented
@radinamatic Yes, we should address the #71 issue. We will take a look on it.

2017-07-19 09:43 UTC, mrpau-eduard commented
Hi @benjaoming I made an update on my script. We can merge it now.
I build a new `sw` to test the updates and it is working.

2017-07-19 10:08 UTC, benjaoming commented
@cpauya responded to your comment - IMO this PR looks good to go :tada:

2017-07-19 10:08 UTC, merged